---
- name: Install snapd
  apt:
    name: snapd
    state: present

- name: Install certbot via snap
  snap:
    name: certbot
    classic: yes

- name: Create certbot symlink
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
