---
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Create fail2ban local configuration
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    backup: yes
  notify: restart fail2ban

- name: Start and enable fail2ban
  systemd:
    name: fail2ban
    state: started
    enabled: yes
