---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install essential system utilities
  apt:
    name:
      - net-tools        # netstat, ifconfig
      - curl            # HTTP client
      - wget            # Download utility
      - vim             # Text editor
      - htop            # Process monitor
      - tree            # Directory listing
      - unzip           # Archive utility
      - zip             # Archive utility
      - git             # Version control
      - lsof            # List open files
      - dnsutils        # DNS utilities (dig, nslookup)
      - iputils-ping    # Ping utility
      - traceroute      # Network diagnostic
      - telnet          # Network testing
      - tcpdump         # Network packet analyzer (optional)
    state: present
    update_cache: no

- name: Install Composer
  include_tasks: composer.yml

- name: Install Fail2ban
  include_tasks: fail2ban.yml
  when: fail2ban_enabled | bool

- name: Install Webmin
  include_tasks: webmin.yml
  when: webmin_enabled | bool

- name: Install phpMyAdmin
  include_tasks: phpmyadmin.yml
  when: phpmyadmin_enabled | bool

- name: Install Certbot
  include_tasks: certbot.yml
  when: certbot_enabled | bool
