---
- name: Install phpMyAdmin
  apt:
    name: phpmyadmin
    state: present

- name: Create phpMyAdmin nginx configuration
  template:
    src: phpmyadmin.conf.j2
    dest: /etc/nginx/conf.d/phpmyadmin.conf
  notify: restart nginx
