---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
