---
- name: Nginx 1.29.1 Installation/Uninstallation Playbook
  hosts: localhost
  connection: local
  become: yes
  vars:
    nginx_user: "www-data"
    nginx_worker_processes: "auto"
    nginx_worker_connections: "1024"
    nginx_keepalive_timeout: "30"
    nginx_client_max_body_size: "64M"
    nginx_server_tokens: "off"
    modsecurity_enabled: true  # Default enable ModSecurity
    # Support both legacy nginx_action and standard action variables
    nginx_action: "{{ action | default('install') }}"

  tasks:
    - name: Include install tasks
      include_tasks: ../roles/nginx/tasks/install.yml
      when: nginx_action == 'install'

    - name: Include uninstall tasks
      include_tasks: ../roles/nginx/tasks/uninstall.yml
      when: nginx_action == 'uninstall'
      
    - name: Display installation status
      debug:
        msg: "Nginx {{ nginx_action }} completed successfully"
      when: nginx_action == 'install'